import { z } from "zod";

export const userSchema = z.object({
  firstName: z.string().min(1, "First name is required"),
  lastName: z.string().min(1, "Last name is required"),
  email: z.string().email("Invalid email"),
  UserSchoolID: z.string().optional(), // Optional - generated by backend as ID
  role: z.enum(["student", "staff"]),
});

export type UserFormData = z.infer<typeof userSchema>;
